### ISSUE TITLE
are you serious?

### ISSUE THREAD

**Issue by johndvorakHR** [kgryte/utils-platform#1]

**Comment by johndvorakHR** [comment]
```node
module.exports = process.platform;
```

**Comment by kgryte** [comment]
@johndvorakHR @dlmather

I will give the benefit of the doubt and assume that the two of you are not just trolling. And because I can empathize with the perspective of considering this an illegitimate module, I justify its existence as follows:
1. Testing. If you need to test code which is platform dependent and branches based on the value of `process.platform`, you have two choices. You either a) deploy to different environments and aggregate code results for an accumulated coverage report or b) you "mock" the environment and force code paths irrespective of the underlying platform. From my POV, I would rather not bother with managing and configuring environments and associated platforms. I would also like to test locally.
   
   For code which branches based on `process.platform`, I could do as follows:
   
   ``` javascript
   var mod = require( './../path/to/my/module' );
   test( 'platform code pathways', function t() {
      var p = process.platform;
   
      // Mock:
      process.platform = 'sunos';
   
      ...
      // Verify platform-dependent behavior...
      ...
   
      // Restore:
      process.platform = p;
   });
   ```
   
   Now, as `process` is a `global`, so, too, is `process.platform`. And therein, lies the rub. What is the problem with the above code?
   
   The code assumes that any dependencies will **not** be adversely affected by modifying core Node.js functionality. But consider the following case,
   
   Some dependency:
   
   ``` javascript
   var fs = require( 'fs' );
   function read() {
       var p;
       if ( process.platform === 'win32' ) {
          p = 'C:\\path\\to\\file';
       } else {
          p = '/path/to/file';
       }
      return fs.readFileSync( p, 'utf8' );
   }
   module.exports = read;
   ```
   
   Test:
   
   ``` javascript
   var mod = require( './../path/to/my/module' );
   test( 'platform code pathways', function t() {
      var p = process.platform;
   
      // Mock:
      process.platform = 'win32';
   
      ...
      // Verify platform-dependent behavior...
      ...
   
      // Restore:
      process.platform = p;
   });
   ```
   
   Let us assume that "some dependency" resides somewhere in the `node_module` tree and is run. Now run the tests on a *nix machine. Your code will `throw`, as the dependency's paths are invalid. Granted, the example is a toy example and can be fixed, but is illustrative of potential problems encountered when testing.
   
    To mitigate potential externalities, one solution is to utilize Node `require` and convert globals to explicit dependencies. For example, 
   
   ``` javascript
    var proxyquire = require( 'proxyquire' );
    test( 'platform code pathways', function t() {
      var mod = proxyquire( './../path/to/my/module', {
          'utils-platform': 'win32'
      });
   
      ...
      // Verify platform-dependent behavior...
      ...
   
   });
   ```
   
   By intercepting Node's `require` for the tested module, we eliminate adverse effects and allow for more efficient unit testing. This is also yet another reason why modularizing everything and doing so in as small of units as possible is so powerful: you can mock and stub with ease and be certain that your unit tests actually test what they are meant to test.
   
   And finally, buried in the above are two hard lessons: treat everything as a hostile environment and **always code [defensively](https://en.wikipedia.org/wiki/Defensive_programming)**.
2. More generally, I am of the opinion that many of the libraries provided by Node core should **not** be part of Node core (e.g., `path`, `utils`, `url`, etc). These libraries can be easily provided and maintained in userland. We already see this (albeit at a slightly larger scale) with [`readable-stream`](https://github.com/nodejs/readable-stream), [`resolve`](https://github.com/substack/node-resolve), [`deep-equal`](https://github.com/substack/node-deep-equal), the eventual deprecation of `utils`, etc.
   
   I believe that if either of you had spent much time actually reading Node's [source](https://github.com/nodejs/node/tree/master/lib) and followed along with the development of the platform, you, too, would realize that many of the utilities could just as easily be modules on NPM, allowing those utilities to be independently required as needed. Many libraries were initially packaged with Node core because NPM was still early days and additional functionality was needed. But now, much functionality is no longer needed due to NPM's growth and often the community's superior solutions. Keeping those modules as part of Node core just leads to bloat.

So I hope this clarifies the rationale behind this module. I create these modules as I need them, often as part of much larger projects, not because I simply feel like making a module.

I will keep this issue open for discussion for a little while longer in case either of you have any further feedback or questions.
